import product01 from "../../assets/ProductImages/phone01.jpg";
export const productData = [
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
  {
    name: "Intel Pentium G6400 10th Gen Special Deal PC",
    categories: "Laptop",
    price: 12,
    image: product01,
  },
];
